#SageMaker Modeling Config
framework:
    name: xgboost
    version: 1.7-1

metaparams:
    endpoint_preds_dir: temp/endpoint_predictions
    instance_type: ml.c6i.4xlarge
    instance_count: 1
    batch_trans_instance_type: ml.c5.9xlarge
    batch_trans_instance_count: 1

script_mode:
    enabled: True
    entry_point: single_model_entry.py
    # entry_point: temporal_cv_model_entry.py
    source_dir: ../src/script_modeling

target:
    classification:
        threshold: 0.2  # if target > {threshold}, class = 1

training:
    model_type: classification  # regression or classification
    eval_metric: aucpr

    #KeyParam Hyperparameters
    hyperparameters:
        num_round: 350
        max_depth: 3
        eta: 0.1
        subsample: 0.8
        colsample_bytree: 0.8
        scale_pos_weight: 100
        early_stopping_rounds: 15

    hpo:  # Hyperparameter Optimization
        enabled: True
        objective_metric_name: eval:cv_auc_pr
        objective_type: maximize
        hyperparameter_ranges:
            max_depth: "IntegerParameter(3,10)"
            eta: "ContinuousParameter(0.01,0.3)"
            subsample: "ContinuousParameter(0.5,1.0)"
        max_jobs: 20
        max_parallel_jobs: 4
        
predicting:
    y_pred_threshold: 0.8 # predictions above this are positive