#SageMaker Modeling Config
framework:
    name: xgboost

training:
    instance_type: ml.m5.large
    instance_count: 1

    #KeyParam Hyperparameters
    hyperparameters:
        objective: reg:squarederror
        num_round: 100
        max_depth: 6
        eta: 0.3
        subsample: 0.8
        colsample_bytree: 0.8
        early_stopping_rounds: 10

predicting:
    instance_type: ml.m5.large
    instance_count: 1