#SageMaker Config

training_data: #SageMaker
    local_s3_root: ../  # where s3_uploads and s3_downloads exist
    local_directory: dda_897_td_column_ordering_v1  # where to load local csvs from
    upload_directory: dda-899-classifier  # new S3 folder name in bucket training_data_processed
    dataset: prod  # Set to prod or dev; determines whether to query core or dev dataset tables

preprocessing: #SageMaker
    fill_na:
        coin_trends: -1
        mktcap: -1
        performance: 0
        scenario|ideal: max
        scenario|worst: min
        scenario|net_perf: mean
        transfers: -1
        transfers: 1

workflow:
    override_existing_models: True  # whether to train models for a date_suffix if one already exists

aws: #SageMaker
    training_bucket: wallet-training-data
    preprocessed_directory: training-data-preprocessed
    modeler_arn: arn:aws:iam::891377123484:role/sagemaker_runner

n_threads: #SageMaker
    upload_all_training_data: 4
    train_all_models: 4