#SageMaker Modeling Config
framework:
    name: xgboost
    version: 1.7-1

metaparams:
    endpoint_preds_dir: temp/endpoint_predictions
    instance_type: ml.m5.large
    instance_count: 1

target:
    classification:
        threshold: 0.05  # if target > {threshold}, class = 1

training:
    model_type: classification  # regression or classification
    eval_metric: auc_pr

    #KeyParam Hyperparameters
    hyperparameters:
        num_round: 100
        max_depth: 6
        eta: 0.3
        subsample: 0.8
        colsample_bytree: 0.8
        early_stopping_rounds: 10

predicting:
    predict_method: endpoint  # endpoint or batch_transform